### ISSUE TITLE
Asynchronous Title Editing

### ISSUE THREAD

**Issue by RogerTangos** [edx/studio-frontend#87]
Calls to the backend are presented as a sychronous to the user, but are effectively synchronous. In the best case, this leads studio users to waste a great amount of time waiting for responses from the server. In the worst case, studio users ignore the need to wait for the server, and accidentally execute different code on the page.

For example, I am currently editing course titles to reflect the length of the video lectures inside them.

From the main page, I click the "Collapse/Expand the section" button, which reveals an input field:

<img width="500" alt="screen shot 2018-01-09 at 12 00 49 pm" src="https://user-images.githubusercontent.com/1609475/34732948-c444cff0-f534-11e7-94fa-4d86d36326c0.png">
 
I make an edit, and I hit return, or click outside of the input field. A "saving" icon appears in the bottom right of my screen:

<img width="213" alt="screen shot 2018-01-09 at 12 04 45 pm" src="https://user-images.githubusercontent.com/1609475/34733133-4f150118-f535-11e7-9063-891614ca3be6.png">

As this is saving, I click a new "Collapse/Expand..." button, and begin editing a new input field.

Now, when the server returns a response to the client, I am kicked out of this input field. My changes are not saved, and my keystrokes go to the window, rather than the input field.

If I click backspace or delete, my browser goes back one page. If I click spacebar, the window scrolls down. Etc.

The round trip time between machine's browser (at MIT) to the servers (at edX) is between 3 and 10 seconds. The UI presents changes as async, but to be frank, given the results of server calls, I'd rather they be synchronous.

This problem represents itself when I am in studio and hit a button, but change tabs before the server responds - Often, the response is lost. Given the long response time, this is an unfortunate, but reasonable strategy for someone making batch changes to course pages.

---
For reference, I'm a content creator (and developer) who has been struggling to use studio to make edits on an existing course.

**Comment by fysheets** [comment]
Thank you for your feedback! This issue should be reported against the [edx-platform](https://github.com/edx/edx-platform) repository as it is not currently within the scope of this repository. Use the steps within the [issue tracking](https://github.com/edx/edx-platform/#issue-tracker) documentation to ensure better visibility and tracking. We will also be removing Issues from this repository and following the same process of the edx-platform repository. The Issues will be removed from this repository tomorrow 1/11/18.

**Comment by fysheets** [comment]
@RogerTangos As noted from the previous comment, we will be removing the Issues from this repository. Thank you again for your feedback, we look forward to seeing it come through in Jira.
